//customer
export const FETCH_CUSTOMER_PENDING = "FETCH_CUSTOMER_PENDING";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_ERROR = "FETCH_CUSTOMER_ERROR";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const ADD_CUSTOMER_ERROR = "ADD_CUSTOMER_ERROR";
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";
export const REMOVE_CUSTOMER_ERROR = "REMOVE_CUSTOMER_ERROR";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const EDIT_CUSTOMER_ERROR = "EDIT_CUSTOMER_ERROR";

//category
export const FETCH_CATEGORY_PENDING = "FETCH_CATEGORY_PENDING";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const REMOVE_CATEGORY_ERROR = "REMOVE_CATEGORY_ERROR";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";

//project
export const FETCH_PROJECT_PENDING = "FETCH_PROJECT_PENDING";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_ERROR = "FETCH_PROJECT_ERROR";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_ERROR = "ADD_PROJECT_ERROR";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const REMOVE_PROJECT_ERROR = "REMOVE_PROJECT_ERROR";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR";

//users
export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const ADD_USER = "ADD_USER";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_ERROR = "REMOVE_USER_ERROR";
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
