import Head from "next/head";
import React, { FC, ReactElement } from "react";
import { ModalCustom } from "../modal-custom/modal-custom";
import { Header } from "../header/header";
import { NavigationMenu } from "../navigation-menu/navigation-menu";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import styles from "./layout.module.css";
import { useState } from "react";

interface Props {
  children: ReactElement;
  title: string;
}

export const MainLayout: FC<Props> = ({ children, title }) => {
  const [isShowNav, setIsShowNav] = useState(true);

  const handleShowNavigation = (isShow): void => {
    console.log(isShow);
    setIsShowNav(isShow);
  };

  const handleHiddenNav = () => {
    setIsShowNav(false);
  };

  return (
    <div className="">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`${styles.main} w-screen bg-gray-200 transition duration-200 ease-in-out`}
      >
        <div
          className={`${styles.navigation} 
                    ${isShowNav ? "mobile:w-2/3 mobile:z-10" : "mobile:w-0"}   
                    ${isShowNav ? "tablet:w-1/3" : "tablet:w-0"}   
                    ${isShowNav ? "laptop:w-1/6" : "laptop:w-0"} 
                    h-screen bg-white float-left shadow-md absolute left-0 inset-y-0 transition duration-200 ease-in-out`}
        >
          <NavigationMenu isShowNav={isShowNav} />
        </div>
        <div
          className={`${styles.header} 
            ${isShowNav ? "mobile:w-3/4" : "mobile:w-full"} 
            ${isShowNav ? "tablet:w-2/3" : "tablet:w-full"} 
            ${isShowNav ? "laptop:w-5/6" : "laptop:w-full"} 
            bg-white float-right shadow-md h-48`}
        >
          <Header
            handleShowNavigation={handleShowNavigation}
            isShowNav={isShowNav}
          />
        </div>

        <div
          className={`
          ${isShowNav ? "mobile:w-full" : "mobile:w-full"} 
            ${isShowNav ? "tablet:w-4/5" : "tablet:w-full"} 
            ${isShowNav ? "laptop:w-5/6" : "laptop:w-w-full"} 
           float-right`}
        >
          {children}
        </div>

        <div
          onClick={handleHiddenNav}
          className={`${styles.overlay} ${
            isShowNav ? "mobile:block mobile:w-1/3" : "mobile:hidden"
          } ${styles.overlay} ${isShowNav ? "tablet:w-2/3" : "mobile:hidden"} 
            ${isShowNav ? "laptop:hidden" : "laptop:hidden"} w-1/3`}
        ></div>
        {/* <div className="h-42 w-6/7 float-right bg-red-200 bottom-0">
          <p>©2012-2021 All rights reserved.</p>
        </div> */}
      </main>

      <ToastContainer></ToastContainer>
    </div>
  );
};
